# -*- coding: utf-8 -*-
"""EP02-E - Currency Conversion

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HpeaoE1jp5gi0KRn0pYjwSFSBEQTMTg2
"""

# EP02-E - Currency Conversion
# Write a program that takes an input value in Brazilian Reais (BRL) and calculates the converted value in three currencies:
# Euro (EUR), United States Dollar (USD), and British Pound Sterling (GBP). Use the following conversion table as a reference:

# BRL 1.00 -> EUR 0.1860
# BRL 1.00 -> USD 0.1949
# BRL 1.00 -> GBP 0.1597

# Conversion Table
brl_to_eur = 0.1860
brl_to_usd = 0.1949
brl_to_gbp = 0.1597

# Asks the user for the value in Brazilian Reais (BRL)
value_brl = float(input("Enter the value in BRL: "))

# Calculates the equivalent value in Euro, United States Dollar, and British Pound Sterling
value_eur = value_brl * brl_to_eur
value_usd = value_brl * brl_to_usd
value_gbp = value_brl * brl_to_gbp

# Displays the formatted results
print("\n BRL {:.2f} -> EUR {:.2f}".format(value_brl, value_eur))
print(" BRL {:.2f} -> USD {:.2f}".format(value_brl, value_usd))
print(" BRL {:.2f} -> GBP {:.2f}".format(value_brl, value_gbp))