name: Bot Fantasma Streamlit

on:
  schedule:
    - cron: '*/30 * * * *'  # roda a cada 30 minutos
  workflow_dispatch:

jobs:
  ping-streamlit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências do sistema e Python
        run: |
          sudo apt-get update
          sudo apt-get install -y libatk-bridge2.0-0 libgtk-3-0 libxss1 libasound2 libnss3 libxcomposite1 libxdamage1 libxrandr2 libgbm1
          pip install playwright
          playwright install

      - name: Executar o bot
        run: |
          python pinger.py
