name: Bot Fantasma Streamlit

on:
  schedule:
    - cron: '*/30 * * * *'  # roda a cada 30 minutos
  workflow_dispatch:        # permite executar manualmente também

jobs:
  ping-streamlit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Playwright
        run: |
          pip install playwright
          playwright install --with-deps

      - name: Executar o bot
        run: python pinger.py
